### ISSUE TITLE
Scoreboard empty lines bug

### ISSUE THREAD

**Issue by Elb1to** [lucko/helper#142]
If the scoreboard contains empty lines, like the example shown below:
```yaml
title: '&b&lHABU'
lines:
- '&7Welcome &b%player%'
- ''
- '&b&lPLAYERS'
- ' &7 • &f%online% players online'
- ''
- '&7elb1to.me'
```

The scoreboard won't show those empty lines, just the first one, the other empty lines won't appear, unless they have a color code in them like the example shown below:
```yaml
title: '&b&lHABU'
lines:
- '&7Welcome &b%player%'
- '&2'
- '&b&lPLAYERS'
- ' &7 • &f%online% players online'
- '&6'
- '&7elb1to.me'
```

Current code:
![image](https://user-images.githubusercontent.com/50537641/203223662-70d2c7e8-12f7-4b8b-b304-a725e3b88d21.png)
